version: '3.8'

services:
  # Production build service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_ENV: production
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/mydatabase
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  # Development build service
  app_dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_ENV: development
    environment:
      - NODE_ENV=development
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo

  # MongoDB service
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    environment:
      DB_NAME: boxing-db
      MONGO_INITDB_DATABASE: boxing-db
    volumes:
      - ./.docker/boxing-training-app-backend/seed-mongodb.js:/docker-entrypoint-initdb.d/seed-mongodb.js
      - mongo-data:/data/db

volumes:
  mongo-data:
